# 服务端口号
server:
  port: 10010
# 配置数据库
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345
#开启log4j打印SQL语句
logging:
  level:
    com:
      javaliang:
        mapper: debug
# mp日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0